### ISSUE TITLE
Make users profile icon clickable

### ISSUE THREAD

**Issue by KaiyaFox** [KaiyaFox/inktail#5]
In the LoginWithDiscordButton component, if the user is logged in, make their profile picture clickable and takes them to their profile page.

**Comment by DavidReque** [comment]
Can i work on this?

**Comment by KaiyaFox** [comment]
> Can i work on this?

Feel free to. Branch off the Dev branch

**Comment by OokamiKitsune** [comment]
Thanks for contributing. Decent implementation. However, the way you implemented the linking was essentially telling the browser to point itself to a new URL and or reload the page. While this is good for linking to external URLs, it's not ideal for navigating within the Next.js framework, as doing it that way, reloads the entire page, also re-mounts all components on that page, causing redundancies in re-mounting already mounted components and triggering its network calls again.

Here is the next.js way:

- Create a function that handles the navigation

` const handleNavigation = (path: string) => {
        router.push(path)
    }`

- In the `return()` use onClick to call the `handleNavigation` function that passes the path to the router.

`<Link onClick={() => handleNavigation(`/user/${userId}`)}>
                                    <Avatar
                                        radius="large"
                                        size="5"
                                        src={user.user_metadata.avatar_url}
                                        fallback={user.user_metadata.custom_claims.global_name.charAt(0)}
                                    />
                                </Link>`
